name: "CD(Docker): Publish stable image"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  ghcr:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ijskoud/ijsblokje:latest
            ghcr.io/ijskoud/ijsblokje:v2
