name: "CD(Docker): Publish stable image"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  ghcr:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # GitHub bot
          - dockerfile: docker/github-bot.dockerfile
            tags: ghcr.io/ijskoud/ijsblokje:github-bot

          # Discord bot
          - dockerfile: docker/discord-bot.dockerfile
            tags: ghcr.io/ijskoud/ijsblokje:discord-bot

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.tags }}
