name: "Ci: Eslint & Build Testing"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Install Node v16
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Install Node v16
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: TypeScript Compiler
        run: yarn build
